coverage:
  status:
    patch:
      default: # status check name
        target: 80% # target coverage of the changes
        threshold: 1% # allow the coverage to drop by <threshold>%
      ignore:
        - "cmd"
    project:
      default: # status check name
        target: 80% # target coverage of the changes

ignore:
  - "**/*.pb.go"
  - "**/*_test.go"
  - "**/*_mock.go"
  - "types"
