// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: substate.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Substate_TxMessage_TxType int32

const (
	Substate_TxMessage_TXTYPE_LEGACY Substate_TxMessage_TxType = 0
	// Berlin hard fork introduced optional access list
	Substate_TxMessage_TXTYPE_ACCESSLIST Substate_TxMessage_TxType = 1
	// London hard fork introduced optional dynamic fee market
	Substate_TxMessage_TXTYPE_DYNAMICFEE Substate_TxMessage_TxType = 2
	// Cancun hard fork introduced optional tx blob
	Substate_TxMessage_TXTYPE_BLOB Substate_TxMessage_TxType = 3
	// eip-7702 introduced setcode transaction type
	Substate_TxMessage_TXTYPE_SETCODE Substate_TxMessage_TxType = 4
)

// Enum value maps for Substate_TxMessage_TxType.
var (
	Substate_TxMessage_TxType_name = map[int32]string{
		0: "TXTYPE_LEGACY",
		1: "TXTYPE_ACCESSLIST",
		2: "TXTYPE_DYNAMICFEE",
		3: "TXTYPE_BLOB",
		4: "TXTYPE_SETCODE",
	}
	Substate_TxMessage_TxType_value = map[string]int32{
		"TXTYPE_LEGACY":     0,
		"TXTYPE_ACCESSLIST": 1,
		"TXTYPE_DYNAMICFEE": 2,
		"TXTYPE_BLOB":       3,
		"TXTYPE_SETCODE":    4,
	}
)

func (x Substate_TxMessage_TxType) Enum() *Substate_TxMessage_TxType {
	p := new(Substate_TxMessage_TxType)
	*p = x
	return p
}

func (x Substate_TxMessage_TxType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Substate_TxMessage_TxType) Descriptor() protoreflect.EnumDescriptor {
	return file_substate_proto_enumTypes[0].Descriptor()
}

func (Substate_TxMessage_TxType) Type() protoreflect.EnumType {
	return &file_substate_proto_enumTypes[0]
}

func (x Substate_TxMessage_TxType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Substate_TxMessage_TxType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Substate_TxMessage_TxType(num)
	return nil
}

// Deprecated: Use Substate_TxMessage_TxType.Descriptor instead.
func (Substate_TxMessage_TxType) EnumDescriptor() ([]byte, []int) {
	return file_substate_proto_rawDescGZIP(), []int{5, 1, 0}
}

type Account struct {
	state   protoimpl.MessageState  `protogen:"open.v1"`
	Nonce   *uint64                 `protobuf:"varint,1,req,name=nonce" json:"nonce,omitempty"`
	Balance []byte                  `protobuf:"bytes,2,req,name=balance" json:"balance,omitempty"`
	Storage []*Account_StorageEntry `protobuf:"bytes,3,rep,name=storage" json:"storage,omitempty"`
	// Types that are valid to be assigned to Contract:
	//
	//	*Account_Code
	//	*Account_CodeHash
	Contract      isAccount_Contract `protobuf_oneof:"contract"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_substate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_substate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_substate_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetNonce() uint64 {
	if x != nil && x.Nonce != nil {
		return *x.Nonce
	}
	return 0
}

func (x *Account) GetBalance() []byte {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *Account) GetStorage() []*Account_StorageEntry {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *Account) GetContract() isAccount_Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *Account) GetCode() []byte {
	if x != nil {
		if x, ok := x.Contract.(*Account_Code); ok {
			return x.Code
		}
	}
	return nil
}

func (x *Account) GetCodeHash() []byte {
	if x != nil {
		if x, ok := x.Contract.(*Account_CodeHash); ok {
			return x.CodeHash
		}
	}
	return nil
}

type isAccount_Contract interface {
	isAccount_Contract()
}

type Account_Code struct {
	Code []byte `protobuf:"bytes,4,opt,name=code,oneof"`
}

type Account_CodeHash struct {
	CodeHash []byte `protobuf:"bytes,5,opt,name=code_hash,json=codeHash,oneof"`
}

func (*Account_Code) isAccount_Contract() {}

func (*Account_CodeHash) isAccount_Contract() {}

type AllocEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
	Account       *Account               `protobuf:"bytes,2,req,name=account" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocEntry) Reset() {
	*x = AllocEntry{}
	mi := &file_substate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocEntry) ProtoMessage() {}

func (x *AllocEntry) ProtoReflect() protoreflect.Message {
	mi := &file_substate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocEntry.ProtoReflect.Descriptor instead.
func (*AllocEntry) Descriptor() ([]byte, []int) {
	return file_substate_proto_rawDescGZIP(), []int{1}
}

func (x *AllocEntry) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *AllocEntry) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type Alloc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alloc         []*AllocEntry          `protobuf:"bytes,1,rep,name=alloc" json:"alloc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alloc) Reset() {
	*x = Alloc{}
	mi := &file_substate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alloc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alloc) ProtoMessage() {}

func (x *Alloc) ProtoReflect() protoreflect.Message {
	mi := &file_substate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alloc.ProtoReflect.Descriptor instead.
func (*Alloc) Descriptor() ([]byte, []int) {
	return file_substate_proto_rawDescGZIP(), []int{2}
}

func (x *Alloc) GetAlloc() []*AllocEntry {
	if x != nil {
		return x.Alloc
	}
	return nil
}

type ExceptionBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  map[int32]*ExceptionTx `protobuf:"bytes,1,rep,name=transactions" json:"transactions,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PreBlock      *Alloc                 `protobuf:"bytes,2,opt,name=preBlock" json:"preBlock,omitempty"`
	PostBlock     *Alloc                 `protobuf:"bytes,3,opt,name=postBlock" json:"postBlock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExceptionBlock) Reset() {
	*x = ExceptionBlock{}
	mi := &file_substate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExceptionBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExceptionBlock) ProtoMessage() {}

func (x *ExceptionBlock) ProtoReflect() protoreflect.Message {
	mi := &file_substate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExceptionBlock.ProtoReflect.Descriptor instead.
func (*ExceptionBlock) Descriptor() ([]byte, []int) {
	return file_substate_proto_rawDescGZIP(), []int{3}
}

func (x *ExceptionBlock) GetTransactions() map[int32]*ExceptionTx {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ExceptionBlock) GetPreBlock() *Alloc {
	if x != nil {
		return x.PreBlock
	}
	return nil
}

func (x *ExceptionBlock) GetPostBlock() *Alloc {
	if x != nil {
		return x.PostBlock
	}
	return nil
}

type ExceptionTx struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PreTransaction  *Alloc                 `protobuf:"bytes,1,opt,name=preTransaction" json:"preTransaction,omitempty"`
	PostTransaction *Alloc                 `protobuf:"bytes,2,opt,name=postTransaction" json:"postTransaction,omitempty"`
	VmException     *bool                  `protobuf:"varint,3,opt,name=vmException" json:"vmException,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExceptionTx) Reset() {
	*x = ExceptionTx{}
	mi := &file_substate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExceptionTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExceptionTx) ProtoMessage() {}

func (x *ExceptionTx) ProtoReflect() protoreflect.Message {
	mi := &file_substate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExceptionTx.ProtoReflect.Descriptor instead.
func (*ExceptionTx) Descriptor() ([]byte, []int) {
	return file_substate_proto_rawDescGZIP(), []int{4}
}

func (x *ExceptionTx) GetPreTransaction() *Alloc {
	if x != nil {
		return x.PreTransaction
	}
	return nil
}

func (x *ExceptionTx) GetPostTransaction() *Alloc {
	if x != nil {
		return x.PostTransaction
	}
	return nil
}

func (x *ExceptionTx) GetVmException() bool {
	if x != nil && x.VmException != nil {
		return *x.VmException
	}
	return false
}

type Substate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputAlloc    *Alloc                 `protobuf:"bytes,1,req,name=input_alloc,json=inputAlloc" json:"input_alloc,omitempty"`
	OutputAlloc   *Alloc                 `protobuf:"bytes,2,req,name=output_alloc,json=outputAlloc" json:"output_alloc,omitempty"`
	BlockEnv      *Substate_BlockEnv     `protobuf:"bytes,3,req,name=block_env,json=blockEnv" json:"block_env,omitempty"`
	TxMessage     *Substate_TxMessage    `protobuf:"bytes,4,req,name=tx_message,json=txMessage" json:"tx_message,omitempty"`
	Result        *Substate_Result       `protobuf:"bytes,5,req,name=result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Substate) Reset() {
	*x = Substate{}
	mi := &file_substate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Substate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Substate) ProtoMessage() {}

func (x *Substate) ProtoReflect() protoreflect.Message {
	mi := &file_substate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Substate.ProtoReflect.Descriptor instead.
func (*Substate) Descriptor() ([]byte, []int) {
	return file_substate_proto_rawDescGZIP(), []int{5}
}

func (x *Substate) GetInputAlloc() *Alloc {
	if x != nil {
		return x.InputAlloc
	}
	return nil
}

func (x *Substate) GetOutputAlloc() *Alloc {
	if x != nil {
		return x.OutputAlloc
	}
	return nil
}

func (x *Substate) GetBlockEnv() *Substate_BlockEnv {
	if x != nil {
		return x.BlockEnv
	}
	return nil
}

func (x *Substate) GetTxMessage() *Substate_TxMessage {
	if x != nil {
		return x.TxMessage
	}
	return nil
}

func (x *Substate) GetResult() *Substate_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type Account_StorageEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account_StorageEntry) Reset() {
	*x = Account_StorageEntry{}
	mi := &file_substate_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account_StorageEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account_StorageEntry) ProtoMessage() {}

func (x *Account_StorageEntry) ProtoReflect() protoreflect.Message {
	mi := &file_substate_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account_StorageEntry.ProtoReflect.Descriptor instead.
func (*Account_StorageEntry) Descriptor() ([]byte, []int) {
	return file_substate_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Account_StorageEntry) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Account_StorageEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Substate_BlockEnv struct {
	state       protoimpl.MessageState              `protogen:"open.v1"`
	Coinbase    []byte                              `protobuf:"bytes,1,req,name=coinbase" json:"coinbase,omitempty"`
	Difficulty  []byte                              `protobuf:"bytes,2,req,name=difficulty" json:"difficulty,omitempty"`
	GasLimit    *uint64                             `protobuf:"varint,3,req,name=gas_limit,json=gasLimit" json:"gas_limit,omitempty"`
	Number      *uint64                             `protobuf:"varint,4,req,name=number" json:"number,omitempty"`
	Timestamp   *uint64                             `protobuf:"varint,5,req,name=timestamp" json:"timestamp,omitempty"`
	BlockHashes []*Substate_BlockEnv_BlockHashEntry `protobuf:"bytes,6,rep,name=block_hashes,json=blockHashes" json:"block_hashes,omitempty"`
	// London hard fork introduced BASEFEE instruction
	BaseFee *wrapperspb.BytesValue `protobuf:"bytes,7,opt,name=base_fee,json=baseFee" json:"base_fee,omitempty"`
	// The Merge hard fork replaced DIFFICULTY with PREVRANDAO
	Random *wrapperspb.BytesValue `protobuf:"bytes,8,opt,name=random" json:"random,omitempty"`
	// Cancun hard fork introduced BLOBBASEFEE instruction
	BlobBaseFee   *wrapperspb.BytesValue `protobuf:"bytes,9,opt,name=blob_base_fee,json=blobBaseFee" json:"blob_base_fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Substate_BlockEnv) Reset() {
	*x = Substate_BlockEnv{}
	mi := &file_substate_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Substate_BlockEnv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Substate_BlockEnv) ProtoMessage() {}

func (x *Substate_BlockEnv) ProtoReflect() protoreflect.Message {
	mi := &file_substate_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Substate_BlockEnv.ProtoReflect.Descriptor instead.
func (*Substate_BlockEnv) Descriptor() ([]byte, []int) {
	return file_substate_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Substate_BlockEnv) GetCoinbase() []byte {
	if x != nil {
		return x.Coinbase
	}
	return nil
}

func (x *Substate_BlockEnv) GetDifficulty() []byte {
	if x != nil {
		return x.Difficulty
	}
	return nil
}

func (x *Substate_BlockEnv) GetGasLimit() uint64 {
	if x != nil && x.GasLimit != nil {
		return *x.GasLimit
	}
	return 0
}

func (x *Substate_BlockEnv) GetNumber() uint64 {
	if x != nil && x.Number != nil {
		return *x.Number
	}
	return 0
}

func (x *Substate_BlockEnv) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *Substate_BlockEnv) GetBlockHashes() []*Substate_BlockEnv_BlockHashEntry {
	if x != nil {
		return x.BlockHashes
	}
	return nil
}

func (x *Substate_BlockEnv) GetBaseFee() *wrapperspb.BytesValue {
	if x != nil {
		return x.BaseFee
	}
	return nil
}

func (x *Substate_BlockEnv) GetRandom() *wrapperspb.BytesValue {
	if x != nil {
		return x.Random
	}
	return nil
}

func (x *Substate_BlockEnv) GetBlobBaseFee() *wrapperspb.BytesValue {
	if x != nil {
		return x.BlobBaseFee
	}
	return nil
}

type Substate_TxMessage struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Nonce    *uint64                `protobuf:"varint,1,req,name=nonce" json:"nonce,omitempty"`
	GasPrice []byte                 `protobuf:"bytes,2,req,name=gas_price,json=gasPrice" json:"gas_price,omitempty"`
	Gas      *uint64                `protobuf:"varint,3,req,name=gas" json:"gas,omitempty"`
	From     []byte                 `protobuf:"bytes,4,req,name=from" json:"from,omitempty"`
	// TxMessage.to is nil for contract creation
	To    *wrapperspb.BytesValue `protobuf:"bytes,5,opt,name=to" json:"to,omitempty"`
	Value []byte                 `protobuf:"bytes,6,req,name=value" json:"value,omitempty"`
	// Types that are valid to be assigned to Input:
	//
	//	*Substate_TxMessage_Data
	//	*Substate_TxMessage_InitCodeHash
	Input      isSubstate_TxMessage_Input            `protobuf_oneof:"input"`
	TxType     *Substate_TxMessage_TxType            `protobuf:"varint,9,req,name=tx_type,json=txType,enum=protobuf.Substate_TxMessage_TxType" json:"tx_type,omitempty"`
	AccessList []*Substate_TxMessage_AccessListEntry `protobuf:"bytes,10,rep,name=access_list,json=accessList" json:"access_list,omitempty"`
	// GasFeeCap, GasTipCap from TXTYPE_DYNAMICFEE
	// nil for tx types prior to TXTYPE_DYNAMICFEE
	GasFeeCap *wrapperspb.BytesValue `protobuf:"bytes,11,opt,name=gas_fee_cap,json=gasFeeCap" json:"gas_fee_cap,omitempty"`
	GasTipCap *wrapperspb.BytesValue `protobuf:"bytes,12,opt,name=gas_tip_cap,json=gasTipCap" json:"gas_tip_cap,omitempty"`
	// BlobFeeCap, BlobHashes, optional Sidecar from TXTYPE_BLOB
	// nil for tx types prior to TXTYPE_BLOB
	BlobGasFeeCap         *wrapperspb.BytesValue                     `protobuf:"bytes,13,opt,name=blob_gas_fee_cap,json=blobGasFeeCap" json:"blob_gas_fee_cap,omitempty"`
	BlobHashes            [][]byte                                   `protobuf:"bytes,14,rep,name=blob_hashes,json=blobHashes" json:"blob_hashes,omitempty"`
	SetCodeAuthorizations []*Substate_TxMessage_SetCodeAuthorization `protobuf:"bytes,15,rep,name=set_code_authorizations,json=setCodeAuthorizations" json:"set_code_authorizations,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Substate_TxMessage) Reset() {
	*x = Substate_TxMessage{}
	mi := &file_substate_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Substate_TxMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Substate_TxMessage) ProtoMessage() {}

func (x *Substate_TxMessage) ProtoReflect() protoreflect.Message {
	mi := &file_substate_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Substate_TxMessage.ProtoReflect.Descriptor instead.
func (*Substate_TxMessage) Descriptor() ([]byte, []int) {
	return file_substate_proto_rawDescGZIP(), []int{5, 1}
}

func (x *Substate_TxMessage) GetNonce() uint64 {
	if x != nil && x.Nonce != nil {
		return *x.Nonce
	}
	return 0
}

func (x *Substate_TxMessage) GetGasPrice() []byte {
	if x != nil {
		return x.GasPrice
	}
	return nil
}

func (x *Substate_TxMessage) GetGas() uint64 {
	if x != nil && x.Gas != nil {
		return *x.Gas
	}
	return 0
}

func (x *Substate_TxMessage) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Substate_TxMessage) GetTo() *wrapperspb.BytesValue {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Substate_TxMessage) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Substate_TxMessage) GetInput() isSubstate_TxMessage_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Substate_TxMessage) GetData() []byte {
	if x != nil {
		if x, ok := x.Input.(*Substate_TxMessage_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *Substate_TxMessage) GetInitCodeHash() []byte {
	if x != nil {
		if x, ok := x.Input.(*Substate_TxMessage_InitCodeHash); ok {
			return x.InitCodeHash
		}
	}
	return nil
}

func (x *Substate_TxMessage) GetTxType() Substate_TxMessage_TxType {
	if x != nil && x.TxType != nil {
		return *x.TxType
	}
	return Substate_TxMessage_TXTYPE_LEGACY
}

func (x *Substate_TxMessage) GetAccessList() []*Substate_TxMessage_AccessListEntry {
	if x != nil {
		return x.AccessList
	}
	return nil
}

func (x *Substate_TxMessage) GetGasFeeCap() *wrapperspb.BytesValue {
	if x != nil {
		return x.GasFeeCap
	}
	return nil
}

func (x *Substate_TxMessage) GetGasTipCap() *wrapperspb.BytesValue {
	if x != nil {
		return x.GasTipCap
	}
	return nil
}

func (x *Substate_TxMessage) GetBlobGasFeeCap() *wrapperspb.BytesValue {
	if x != nil {
		return x.BlobGasFeeCap
	}
	return nil
}

func (x *Substate_TxMessage) GetBlobHashes() [][]byte {
	if x != nil {
		return x.BlobHashes
	}
	return nil
}

func (x *Substate_TxMessage) GetSetCodeAuthorizations() []*Substate_TxMessage_SetCodeAuthorization {
	if x != nil {
		return x.SetCodeAuthorizations
	}
	return nil
}

type isSubstate_TxMessage_Input interface {
	isSubstate_TxMessage_Input()
}

type Substate_TxMessage_Data struct {
	Data []byte `protobuf:"bytes,7,opt,name=data,oneof"`
}

type Substate_TxMessage_InitCodeHash struct {
	InitCodeHash []byte `protobuf:"bytes,8,opt,name=init_code_hash,json=initCodeHash,oneof"`
}

func (*Substate_TxMessage_Data) isSubstate_TxMessage_Input() {}

func (*Substate_TxMessage_InitCodeHash) isSubstate_TxMessage_Input() {}

type Substate_Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *uint64                `protobuf:"varint,1,req,name=status" json:"status,omitempty"`
	Bloom         []byte                 `protobuf:"bytes,2,req,name=bloom" json:"bloom,omitempty"`
	Logs          []*Substate_Result_Log `protobuf:"bytes,3,rep,name=logs" json:"logs,omitempty"`
	GasUsed       *uint64                `protobuf:"varint,4,req,name=gas_used,json=gasUsed" json:"gas_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Substate_Result) Reset() {
	*x = Substate_Result{}
	mi := &file_substate_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Substate_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Substate_Result) ProtoMessage() {}

func (x *Substate_Result) ProtoReflect() protoreflect.Message {
	mi := &file_substate_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Substate_Result.ProtoReflect.Descriptor instead.
func (*Substate_Result) Descriptor() ([]byte, []int) {
	return file_substate_proto_rawDescGZIP(), []int{5, 2}
}

func (x *Substate_Result) GetStatus() uint64 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *Substate_Result) GetBloom() []byte {
	if x != nil {
		return x.Bloom
	}
	return nil
}

func (x *Substate_Result) GetLogs() []*Substate_Result_Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *Substate_Result) GetGasUsed() uint64 {
	if x != nil && x.GasUsed != nil {
		return *x.GasUsed
	}
	return 0
}

type Substate_BlockEnv_BlockHashEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *uint64                `protobuf:"varint,1,req,name=key" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Substate_BlockEnv_BlockHashEntry) Reset() {
	*x = Substate_BlockEnv_BlockHashEntry{}
	mi := &file_substate_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Substate_BlockEnv_BlockHashEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Substate_BlockEnv_BlockHashEntry) ProtoMessage() {}

func (x *Substate_BlockEnv_BlockHashEntry) ProtoReflect() protoreflect.Message {
	mi := &file_substate_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Substate_BlockEnv_BlockHashEntry.ProtoReflect.Descriptor instead.
func (*Substate_BlockEnv_BlockHashEntry) Descriptor() ([]byte, []int) {
	return file_substate_proto_rawDescGZIP(), []int{5, 0, 0}
}

func (x *Substate_BlockEnv_BlockHashEntry) GetKey() uint64 {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return 0
}

func (x *Substate_BlockEnv_BlockHashEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// AccessList from TXTYPE_ACCESSLIST
// nil for tx types prior to TXTYPE_ACCESSLIST
type Substate_TxMessage_AccessListEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
	StorageKeys   [][]byte               `protobuf:"bytes,2,rep,name=storage_keys,json=storageKeys" json:"storage_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Substate_TxMessage_AccessListEntry) Reset() {
	*x = Substate_TxMessage_AccessListEntry{}
	mi := &file_substate_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Substate_TxMessage_AccessListEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Substate_TxMessage_AccessListEntry) ProtoMessage() {}

func (x *Substate_TxMessage_AccessListEntry) ProtoReflect() protoreflect.Message {
	mi := &file_substate_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Substate_TxMessage_AccessListEntry.ProtoReflect.Descriptor instead.
func (*Substate_TxMessage_AccessListEntry) Descriptor() ([]byte, []int) {
	return file_substate_proto_rawDescGZIP(), []int{5, 1, 0}
}

func (x *Substate_TxMessage_AccessListEntry) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Substate_TxMessage_AccessListEntry) GetStorageKeys() [][]byte {
	if x != nil {
		return x.StorageKeys
	}
	return nil
}

type Substate_TxMessage_SetCodeAuthorization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       []byte                 `protobuf:"bytes,1,req,name=chain_id,json=chainId" json:"chain_id,omitempty"`
	Address       []byte                 `protobuf:"bytes,2,req,name=address" json:"address,omitempty"`
	Nonce         *uint64                `protobuf:"varint,3,req,name=nonce" json:"nonce,omitempty"`
	V             []byte                 `protobuf:"bytes,4,req,name=v" json:"v,omitempty"`
	R             []byte                 `protobuf:"bytes,5,req,name=r" json:"r,omitempty"`
	S             []byte                 `protobuf:"bytes,6,req,name=s" json:"s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Substate_TxMessage_SetCodeAuthorization) Reset() {
	*x = Substate_TxMessage_SetCodeAuthorization{}
	mi := &file_substate_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Substate_TxMessage_SetCodeAuthorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Substate_TxMessage_SetCodeAuthorization) ProtoMessage() {}

func (x *Substate_TxMessage_SetCodeAuthorization) ProtoReflect() protoreflect.Message {
	mi := &file_substate_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Substate_TxMessage_SetCodeAuthorization.ProtoReflect.Descriptor instead.
func (*Substate_TxMessage_SetCodeAuthorization) Descriptor() ([]byte, []int) {
	return file_substate_proto_rawDescGZIP(), []int{5, 1, 1}
}

func (x *Substate_TxMessage_SetCodeAuthorization) GetChainId() []byte {
	if x != nil {
		return x.ChainId
	}
	return nil
}

func (x *Substate_TxMessage_SetCodeAuthorization) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Substate_TxMessage_SetCodeAuthorization) GetNonce() uint64 {
	if x != nil && x.Nonce != nil {
		return *x.Nonce
	}
	return 0
}

func (x *Substate_TxMessage_SetCodeAuthorization) GetV() []byte {
	if x != nil {
		return x.V
	}
	return nil
}

func (x *Substate_TxMessage_SetCodeAuthorization) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *Substate_TxMessage_SetCodeAuthorization) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

type Substate_Result_Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
	Topics        [][]byte               `protobuf:"bytes,2,rep,name=topics" json:"topics,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,req,name=data" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Substate_Result_Log) Reset() {
	*x = Substate_Result_Log{}
	mi := &file_substate_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Substate_Result_Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Substate_Result_Log) ProtoMessage() {}

func (x *Substate_Result_Log) ProtoReflect() protoreflect.Message {
	mi := &file_substate_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Substate_Result_Log.ProtoReflect.Descriptor instead.
func (*Substate_Result_Log) Descriptor() ([]byte, []int) {
	return file_substate_proto_rawDescGZIP(), []int{5, 2, 0}
}

func (x *Substate_Result_Log) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Substate_Result_Log) GetTopics() [][]byte {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *Substate_Result_Log) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_substate_proto protoreflect.FileDescriptor

const file_substate_proto_rawDesc = "" +
	"\n" +
	"\x0esubstate.proto\x12\bprotobuf\x1a\x1egoogle/protobuf/wrappers.proto\"\xec\x01\n" +
	"\aAccount\x12\x14\n" +
	"\x05nonce\x18\x01 \x02(\x04R\x05nonce\x12\x18\n" +
	"\abalance\x18\x02 \x02(\fR\abalance\x128\n" +
	"\astorage\x18\x03 \x03(\v2\x1e.protobuf.Account.StorageEntryR\astorage\x12\x14\n" +
	"\x04code\x18\x04 \x01(\fH\x00R\x04code\x12\x1d\n" +
	"\tcode_hash\x18\x05 \x01(\fH\x00R\bcodeHash\x1a6\n" +
	"\fStorageEntry\x12\x10\n" +
	"\x03key\x18\x01 \x02(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x02(\fR\x05valueB\n" +
	"\n" +
	"\bcontract\"S\n" +
	"\n" +
	"AllocEntry\x12\x18\n" +
	"\aaddress\x18\x01 \x02(\fR\aaddress\x12+\n" +
	"\aaccount\x18\x02 \x02(\v2\x11.protobuf.AccountR\aaccount\"3\n" +
	"\x05Alloc\x12*\n" +
	"\x05alloc\x18\x01 \x03(\v2\x14.protobuf.AllocEntryR\x05alloc\"\x94\x02\n" +
	"\x0eExceptionBlock\x12N\n" +
	"\ftransactions\x18\x01 \x03(\v2*.protobuf.ExceptionBlock.TransactionsEntryR\ftransactions\x12+\n" +
	"\bpreBlock\x18\x02 \x01(\v2\x0f.protobuf.AllocR\bpreBlock\x12-\n" +
	"\tpostBlock\x18\x03 \x01(\v2\x0f.protobuf.AllocR\tpostBlock\x1aV\n" +
	"\x11TransactionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.protobuf.ExceptionTxR\x05value:\x028\x01\"\xa3\x01\n" +
	"\vExceptionTx\x127\n" +
	"\x0epreTransaction\x18\x01 \x01(\v2\x0f.protobuf.AllocR\x0epreTransaction\x129\n" +
	"\x0fpostTransaction\x18\x02 \x01(\v2\x0f.protobuf.AllocR\x0fpostTransaction\x12 \n" +
	"\vvmException\x18\x03 \x01(\bR\vvmException\"\xd9\x0f\n" +
	"\bSubstate\x120\n" +
	"\vinput_alloc\x18\x01 \x02(\v2\x0f.protobuf.AllocR\n" +
	"inputAlloc\x122\n" +
	"\foutput_alloc\x18\x02 \x02(\v2\x0f.protobuf.AllocR\voutputAlloc\x128\n" +
	"\tblock_env\x18\x03 \x02(\v2\x1b.protobuf.Substate.BlockEnvR\bblockEnv\x12;\n" +
	"\n" +
	"tx_message\x18\x04 \x02(\v2\x1c.protobuf.Substate.TxMessageR\ttxMessage\x121\n" +
	"\x06result\x18\x05 \x02(\v2\x19.protobuf.Substate.ResultR\x06result\x1a\xd0\x03\n" +
	"\bBlockEnv\x12\x1a\n" +
	"\bcoinbase\x18\x01 \x02(\fR\bcoinbase\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x02 \x02(\fR\n" +
	"difficulty\x12\x1b\n" +
	"\tgas_limit\x18\x03 \x02(\x04R\bgasLimit\x12\x16\n" +
	"\x06number\x18\x04 \x02(\x04R\x06number\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x02(\x04R\ttimestamp\x12M\n" +
	"\fblock_hashes\x18\x06 \x03(\v2*.protobuf.Substate.BlockEnv.BlockHashEntryR\vblockHashes\x126\n" +
	"\bbase_fee\x18\a \x01(\v2\x1b.google.protobuf.BytesValueR\abaseFee\x123\n" +
	"\x06random\x18\b \x01(\v2\x1b.google.protobuf.BytesValueR\x06random\x12?\n" +
	"\rblob_base_fee\x18\t \x01(\v2\x1b.google.protobuf.BytesValueR\vblobBaseFee\x1a8\n" +
	"\x0eBlockHashEntry\x12\x10\n" +
	"\x03key\x18\x01 \x02(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x02(\fR\x05value\x1a\x95\b\n" +
	"\tTxMessage\x12\x14\n" +
	"\x05nonce\x18\x01 \x02(\x04R\x05nonce\x12\x1b\n" +
	"\tgas_price\x18\x02 \x02(\fR\bgasPrice\x12\x10\n" +
	"\x03gas\x18\x03 \x02(\x04R\x03gas\x12\x12\n" +
	"\x04from\x18\x04 \x02(\fR\x04from\x12+\n" +
	"\x02to\x18\x05 \x01(\v2\x1b.google.protobuf.BytesValueR\x02to\x12\x14\n" +
	"\x05value\x18\x06 \x02(\fR\x05value\x12\x14\n" +
	"\x04data\x18\a \x01(\fH\x00R\x04data\x12&\n" +
	"\x0einit_code_hash\x18\b \x01(\fH\x00R\finitCodeHash\x12<\n" +
	"\atx_type\x18\t \x02(\x0e2#.protobuf.Substate.TxMessage.TxTypeR\x06txType\x12M\n" +
	"\vaccess_list\x18\n" +
	" \x03(\v2,.protobuf.Substate.TxMessage.AccessListEntryR\n" +
	"accessList\x12;\n" +
	"\vgas_fee_cap\x18\v \x01(\v2\x1b.google.protobuf.BytesValueR\tgasFeeCap\x12;\n" +
	"\vgas_tip_cap\x18\f \x01(\v2\x1b.google.protobuf.BytesValueR\tgasTipCap\x12D\n" +
	"\x10blob_gas_fee_cap\x18\r \x01(\v2\x1b.google.protobuf.BytesValueR\rblobGasFeeCap\x12\x1f\n" +
	"\vblob_hashes\x18\x0e \x03(\fR\n" +
	"blobHashes\x12i\n" +
	"\x17set_code_authorizations\x18\x0f \x03(\v21.protobuf.Substate.TxMessage.SetCodeAuthorizationR\x15setCodeAuthorizations\x1aN\n" +
	"\x0fAccessListEntry\x12\x18\n" +
	"\aaddress\x18\x01 \x02(\fR\aaddress\x12!\n" +
	"\fstorage_keys\x18\x02 \x03(\fR\vstorageKeys\x1a\x8b\x01\n" +
	"\x14SetCodeAuthorization\x12\x19\n" +
	"\bchain_id\x18\x01 \x02(\fR\achainId\x12\x18\n" +
	"\aaddress\x18\x02 \x02(\fR\aaddress\x12\x14\n" +
	"\x05nonce\x18\x03 \x02(\x04R\x05nonce\x12\f\n" +
	"\x01v\x18\x04 \x02(\fR\x01v\x12\f\n" +
	"\x01r\x18\x05 \x02(\fR\x01r\x12\f\n" +
	"\x01s\x18\x06 \x02(\fR\x01s\"n\n" +
	"\x06TxType\x12\x11\n" +
	"\rTXTYPE_LEGACY\x10\x00\x12\x15\n" +
	"\x11TXTYPE_ACCESSLIST\x10\x01\x12\x15\n" +
	"\x11TXTYPE_DYNAMICFEE\x10\x02\x12\x0f\n" +
	"\vTXTYPE_BLOB\x10\x03\x12\x12\n" +
	"\x0eTXTYPE_SETCODE\x10\x04B\a\n" +
	"\x05input\x1a\xd1\x01\n" +
	"\x06Result\x12\x16\n" +
	"\x06status\x18\x01 \x02(\x04R\x06status\x12\x14\n" +
	"\x05bloom\x18\x02 \x02(\fR\x05bloom\x121\n" +
	"\x04logs\x18\x03 \x03(\v2\x1d.protobuf.Substate.Result.LogR\x04logs\x12\x19\n" +
	"\bgas_used\x18\x04 \x02(\x04R\agasUsed\x1aK\n" +
	"\x03Log\x12\x18\n" +
	"\aaddress\x18\x01 \x02(\fR\aaddress\x12\x16\n" +
	"\x06topics\x18\x02 \x03(\fR\x06topics\x12\x12\n" +
	"\x04data\x18\x03 \x02(\fR\x04dataB\rZ\v../protobuf"

var (
	file_substate_proto_rawDescOnce sync.Once
	file_substate_proto_rawDescData []byte
)

func file_substate_proto_rawDescGZIP() []byte {
	file_substate_proto_rawDescOnce.Do(func() {
		file_substate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_substate_proto_rawDesc), len(file_substate_proto_rawDesc)))
	})
	return file_substate_proto_rawDescData
}

var file_substate_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_substate_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_substate_proto_goTypes = []any{
	(Substate_TxMessage_TxType)(0),                  // 0: protobuf.Substate.TxMessage.TxType
	(*Account)(nil),                                 // 1: protobuf.Account
	(*AllocEntry)(nil),                              // 2: protobuf.AllocEntry
	(*Alloc)(nil),                                   // 3: protobuf.Alloc
	(*ExceptionBlock)(nil),                          // 4: protobuf.ExceptionBlock
	(*ExceptionTx)(nil),                             // 5: protobuf.ExceptionTx
	(*Substate)(nil),                                // 6: protobuf.Substate
	(*Account_StorageEntry)(nil),                    // 7: protobuf.Account.StorageEntry
	nil,                                             // 8: protobuf.ExceptionBlock.TransactionsEntry
	(*Substate_BlockEnv)(nil),                       // 9: protobuf.Substate.BlockEnv
	(*Substate_TxMessage)(nil),                      // 10: protobuf.Substate.TxMessage
	(*Substate_Result)(nil),                         // 11: protobuf.Substate.Result
	(*Substate_BlockEnv_BlockHashEntry)(nil),        // 12: protobuf.Substate.BlockEnv.BlockHashEntry
	(*Substate_TxMessage_AccessListEntry)(nil),      // 13: protobuf.Substate.TxMessage.AccessListEntry
	(*Substate_TxMessage_SetCodeAuthorization)(nil), // 14: protobuf.Substate.TxMessage.SetCodeAuthorization
	(*Substate_Result_Log)(nil),                     // 15: protobuf.Substate.Result.Log
	(*wrapperspb.BytesValue)(nil),                   // 16: google.protobuf.BytesValue
}
var file_substate_proto_depIdxs = []int32{
	7,  // 0: protobuf.Account.storage:type_name -> protobuf.Account.StorageEntry
	1,  // 1: protobuf.AllocEntry.account:type_name -> protobuf.Account
	2,  // 2: protobuf.Alloc.alloc:type_name -> protobuf.AllocEntry
	8,  // 3: protobuf.ExceptionBlock.transactions:type_name -> protobuf.ExceptionBlock.TransactionsEntry
	3,  // 4: protobuf.ExceptionBlock.preBlock:type_name -> protobuf.Alloc
	3,  // 5: protobuf.ExceptionBlock.postBlock:type_name -> protobuf.Alloc
	3,  // 6: protobuf.ExceptionTx.preTransaction:type_name -> protobuf.Alloc
	3,  // 7: protobuf.ExceptionTx.postTransaction:type_name -> protobuf.Alloc
	3,  // 8: protobuf.Substate.input_alloc:type_name -> protobuf.Alloc
	3,  // 9: protobuf.Substate.output_alloc:type_name -> protobuf.Alloc
	9,  // 10: protobuf.Substate.block_env:type_name -> protobuf.Substate.BlockEnv
	10, // 11: protobuf.Substate.tx_message:type_name -> protobuf.Substate.TxMessage
	11, // 12: protobuf.Substate.result:type_name -> protobuf.Substate.Result
	5,  // 13: protobuf.ExceptionBlock.TransactionsEntry.value:type_name -> protobuf.ExceptionTx
	12, // 14: protobuf.Substate.BlockEnv.block_hashes:type_name -> protobuf.Substate.BlockEnv.BlockHashEntry
	16, // 15: protobuf.Substate.BlockEnv.base_fee:type_name -> google.protobuf.BytesValue
	16, // 16: protobuf.Substate.BlockEnv.random:type_name -> google.protobuf.BytesValue
	16, // 17: protobuf.Substate.BlockEnv.blob_base_fee:type_name -> google.protobuf.BytesValue
	16, // 18: protobuf.Substate.TxMessage.to:type_name -> google.protobuf.BytesValue
	0,  // 19: protobuf.Substate.TxMessage.tx_type:type_name -> protobuf.Substate.TxMessage.TxType
	13, // 20: protobuf.Substate.TxMessage.access_list:type_name -> protobuf.Substate.TxMessage.AccessListEntry
	16, // 21: protobuf.Substate.TxMessage.gas_fee_cap:type_name -> google.protobuf.BytesValue
	16, // 22: protobuf.Substate.TxMessage.gas_tip_cap:type_name -> google.protobuf.BytesValue
	16, // 23: protobuf.Substate.TxMessage.blob_gas_fee_cap:type_name -> google.protobuf.BytesValue
	14, // 24: protobuf.Substate.TxMessage.set_code_authorizations:type_name -> protobuf.Substate.TxMessage.SetCodeAuthorization
	15, // 25: protobuf.Substate.Result.logs:type_name -> protobuf.Substate.Result.Log
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_substate_proto_init() }
func file_substate_proto_init() {
	if File_substate_proto != nil {
		return
	}
	file_substate_proto_msgTypes[0].OneofWrappers = []any{
		(*Account_Code)(nil),
		(*Account_CodeHash)(nil),
	}
	file_substate_proto_msgTypes[9].OneofWrappers = []any{
		(*Substate_TxMessage_Data)(nil),
		(*Substate_TxMessage_InitCodeHash)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_substate_proto_rawDesc), len(file_substate_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_substate_proto_goTypes,
		DependencyIndexes: file_substate_proto_depIdxs,
		EnumInfos:         file_substate_proto_enumTypes,
		MessageInfos:      file_substate_proto_msgTypes,
	}.Build()
	File_substate_proto = out.File
	file_substate_proto_goTypes = nil
	file_substate_proto_depIdxs = nil
}
