// Code generated by MockGen. DO NOT EDIT.
// Source: block_hash_db.go
//
// Generated by this command:
//
//	mockgen -source=block_hash_db.go -destination=./block_hash_db_mock.go -package=db
//

// Package db is a generated GoMock package.
package db

import (
	reflect "reflect"

	types "github.com/0xsoniclabs/substate/types"
	leveldb "github.com/syndtr/goleveldb/leveldb"
	iterator "github.com/syndtr/goleveldb/leveldb/iterator"
	util "github.com/syndtr/goleveldb/leveldb/util"
	gomock "go.uber.org/mock/gomock"
)

// MockBlockHashDB is a mock of BlockHashDB interface.
type MockBlockHashDB struct {
	ctrl     *gomock.Controller
	recorder *MockBlockHashDBMockRecorder
}

// MockBlockHashDBMockRecorder is the mock recorder for MockBlockHashDB.
type MockBlockHashDBMockRecorder struct {
	mock *MockBlockHashDB
}

// NewMockBlockHashDB creates a new mock instance.
func NewMockBlockHashDB(ctrl *gomock.Controller) *MockBlockHashDB {
	mock := &MockBlockHashDB{ctrl: ctrl}
	mock.recorder = &MockBlockHashDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockHashDB) EXPECT() *MockBlockHashDBMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockBlockHashDB) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockBlockHashDBMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockBlockHashDB)(nil).Close))
}

// Compact mocks base method.
func (m *MockBlockHashDB) Compact(start, limit []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compact", start, limit)
	ret0, _ := ret[0].(error)
	return ret0
}

// Compact indicates an expected call of Compact.
func (mr *MockBlockHashDBMockRecorder) Compact(start, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compact", reflect.TypeOf((*MockBlockHashDB)(nil).Compact), start, limit)
}

// Delete mocks base method.
func (m *MockBlockHashDB) Delete(key []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBlockHashDBMockRecorder) Delete(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBlockHashDB)(nil).Delete), key)
}

// Get mocks base method.
func (m *MockBlockHashDB) Get(arg0 []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBlockHashDBMockRecorder) Get(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBlockHashDB)(nil).Get), arg0)
}

// GetBackend mocks base method.
func (m *MockBlockHashDB) GetBackend() DbAdapter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackend")
	ret0, _ := ret[0].(DbAdapter)
	return ret0
}

// GetBackend indicates an expected call of GetBackend.
func (mr *MockBlockHashDBMockRecorder) GetBackend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackend", reflect.TypeOf((*MockBlockHashDB)(nil).GetBackend))
}

// GetBlockHash mocks base method.
func (m *MockBlockHashDB) GetBlockHash(block int) (types.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockHash", block)
	ret0, _ := ret[0].(types.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockHash indicates an expected call of GetBlockHash.
func (mr *MockBlockHashDBMockRecorder) GetBlockHash(block any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockHash", reflect.TypeOf((*MockBlockHashDB)(nil).GetBlockHash), block)
}

// GetFirstKey mocks base method.
func (m *MockBlockHashDB) GetFirstKey() (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstKey")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFirstKey indicates an expected call of GetFirstKey.
func (mr *MockBlockHashDBMockRecorder) GetFirstKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstKey", reflect.TypeOf((*MockBlockHashDB)(nil).GetFirstKey))
}

// GetLastKey mocks base method.
func (m *MockBlockHashDB) GetLastKey() (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastKey")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastKey indicates an expected call of GetLastKey.
func (mr *MockBlockHashDBMockRecorder) GetLastKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastKey", reflect.TypeOf((*MockBlockHashDB)(nil).GetLastKey))
}

// GetSubstateEncoding mocks base method.
func (m *MockBlockHashDB) GetSubstateEncoding() SubstateEncodingSchema {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubstateEncoding")
	ret0, _ := ret[0].(SubstateEncodingSchema)
	return ret0
}

// GetSubstateEncoding indicates an expected call of GetSubstateEncoding.
func (mr *MockBlockHashDBMockRecorder) GetSubstateEncoding() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubstateEncoding", reflect.TypeOf((*MockBlockHashDB)(nil).GetSubstateEncoding))
}

// Has mocks base method.
func (m *MockBlockHashDB) Has(arg0 []byte) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Has", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Has indicates an expected call of Has.
func (mr *MockBlockHashDBMockRecorder) Has(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Has", reflect.TypeOf((*MockBlockHashDB)(nil).Has), arg0)
}

// NewBatch mocks base method.
func (m *MockBlockHashDB) NewBatch() Batch {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewBatch")
	ret0, _ := ret[0].(Batch)
	return ret0
}

// NewBatch indicates an expected call of NewBatch.
func (mr *MockBlockHashDBMockRecorder) NewBatch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewBatch", reflect.TypeOf((*MockBlockHashDB)(nil).NewBatch))
}

// NewIterator mocks base method.
func (m *MockBlockHashDB) NewIterator(prefix, start []byte) iterator.Iterator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewIterator", prefix, start)
	ret0, _ := ret[0].(iterator.Iterator)
	return ret0
}

// NewIterator indicates an expected call of NewIterator.
func (mr *MockBlockHashDBMockRecorder) NewIterator(prefix, start any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewIterator", reflect.TypeOf((*MockBlockHashDB)(nil).NewIterator), prefix, start)
}

// Put mocks base method.
func (m *MockBlockHashDB) Put(key, value []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockBlockHashDBMockRecorder) Put(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockBlockHashDB)(nil).Put), key, value)
}

// PutBlockHash mocks base method.
func (m *MockBlockHashDB) PutBlockHash(blockNumber uint64, blockHash []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutBlockHash", blockNumber, blockHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutBlockHash indicates an expected call of PutBlockHash.
func (mr *MockBlockHashDBMockRecorder) PutBlockHash(blockNumber, blockHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutBlockHash", reflect.TypeOf((*MockBlockHashDB)(nil).PutBlockHash), blockNumber, blockHash)
}

// PutBlockHashString mocks base method.
func (m *MockBlockHashDB) PutBlockHashString(blockNumberHex, blockHashString string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutBlockHashString", blockNumberHex, blockHashString)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutBlockHashString indicates an expected call of PutBlockHashString.
func (mr *MockBlockHashDBMockRecorder) PutBlockHashString(blockNumberHex, blockHashString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutBlockHashString", reflect.TypeOf((*MockBlockHashDB)(nil).PutBlockHashString), blockNumberHex, blockHashString)
}

// Stat mocks base method.
func (m *MockBlockHashDB) Stat(property string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", property)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockBlockHashDBMockRecorder) Stat(property any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockBlockHashDB)(nil).Stat), property)
}

// binarySearchForLastPrefixKey mocks base method.
func (m *MockBlockHashDB) binarySearchForLastPrefixKey(lastKeyPrefix []byte) (byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "binarySearchForLastPrefixKey", lastKeyPrefix)
	ret0, _ := ret[0].(byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// binarySearchForLastPrefixKey indicates an expected call of binarySearchForLastPrefixKey.
func (mr *MockBlockHashDBMockRecorder) binarySearchForLastPrefixKey(lastKeyPrefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "binarySearchForLastPrefixKey", reflect.TypeOf((*MockBlockHashDB)(nil).binarySearchForLastPrefixKey), lastKeyPrefix)
}

// hasKeyValuesFor mocks base method.
func (m *MockBlockHashDB) hasKeyValuesFor(prefix, start []byte) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "hasKeyValuesFor", prefix, start)
	ret0, _ := ret[0].(bool)
	return ret0
}

// hasKeyValuesFor indicates an expected call of hasKeyValuesFor.
func (mr *MockBlockHashDBMockRecorder) hasKeyValuesFor(prefix, start any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "hasKeyValuesFor", reflect.TypeOf((*MockBlockHashDB)(nil).hasKeyValuesFor), prefix, start)
}

// newIterator mocks base method.
func (m *MockBlockHashDB) newIterator(r *util.Range) iterator.Iterator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "newIterator", r)
	ret0, _ := ret[0].(iterator.Iterator)
	return ret0
}

// newIterator indicates an expected call of newIterator.
func (mr *MockBlockHashDBMockRecorder) newIterator(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "newIterator", reflect.TypeOf((*MockBlockHashDB)(nil).newIterator), r)
}

// stats mocks base method.
func (m *MockBlockHashDB) stats(stats *leveldb.DBStats) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "stats", stats)
	ret0, _ := ret[0].(error)
	return ret0
}

// stats indicates an expected call of stats.
func (mr *MockBlockHashDBMockRecorder) stats(stats any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "stats", reflect.TypeOf((*MockBlockHashDB)(nil).stats), stats)
}
