// Code generated by MockGen. DO NOT EDIT.
// Source: destroyed_account_db.go
//
// Generated by this command:
//
//	mockgen -source=destroyed_account_db.go -destination=./destroyed_account_db_mock.go -package=db
//

// Package db is a generated GoMock package.
package db

import (
	reflect "reflect"

	types "github.com/0xsoniclabs/substate/types"
	leveldb "github.com/syndtr/goleveldb/leveldb"
	iterator "github.com/syndtr/goleveldb/leveldb/iterator"
	util "github.com/syndtr/goleveldb/leveldb/util"
	gomock "go.uber.org/mock/gomock"
)

// MockDestroyedAccountDB is a mock of DestroyedAccountDB interface.
type MockDestroyedAccountDB struct {
	ctrl     *gomock.Controller
	recorder *MockDestroyedAccountDBMockRecorder
	isgomock struct{}
}

// MockDestroyedAccountDBMockRecorder is the mock recorder for MockDestroyedAccountDB.
type MockDestroyedAccountDBMockRecorder struct {
	mock *MockDestroyedAccountDB
}

// NewMockDestroyedAccountDB creates a new mock instance.
func NewMockDestroyedAccountDB(ctrl *gomock.Controller) *MockDestroyedAccountDB {
	mock := &MockDestroyedAccountDB{ctrl: ctrl}
	mock.recorder = &MockDestroyedAccountDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDestroyedAccountDB) EXPECT() *MockDestroyedAccountDBMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDestroyedAccountDB) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDestroyedAccountDBMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDestroyedAccountDB)(nil).Close))
}

// Compact mocks base method.
func (m *MockDestroyedAccountDB) Compact(start, limit []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compact", start, limit)
	ret0, _ := ret[0].(error)
	return ret0
}

// Compact indicates an expected call of Compact.
func (mr *MockDestroyedAccountDBMockRecorder) Compact(start, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compact", reflect.TypeOf((*MockDestroyedAccountDB)(nil).Compact), start, limit)
}

// Delete mocks base method.
func (m *MockDestroyedAccountDB) Delete(key []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDestroyedAccountDBMockRecorder) Delete(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDestroyedAccountDB)(nil).Delete), key)
}

// Get mocks base method.
func (m *MockDestroyedAccountDB) Get(arg0 []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDestroyedAccountDBMockRecorder) Get(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDestroyedAccountDB)(nil).Get), arg0)
}

// GetAccountsDestroyedInRange mocks base method.
func (m *MockDestroyedAccountDB) GetAccountsDestroyedInRange(from, to uint64) ([]types.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountsDestroyedInRange", from, to)
	ret0, _ := ret[0].([]types.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountsDestroyedInRange indicates an expected call of GetAccountsDestroyedInRange.
func (mr *MockDestroyedAccountDBMockRecorder) GetAccountsDestroyedInRange(from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountsDestroyedInRange", reflect.TypeOf((*MockDestroyedAccountDB)(nil).GetAccountsDestroyedInRange), from, to)
}

// GetBackend mocks base method.
func (m *MockDestroyedAccountDB) GetBackend() DbAdapter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackend")
	ret0, _ := ret[0].(DbAdapter)
	return ret0
}

// GetBackend indicates an expected call of GetBackend.
func (mr *MockDestroyedAccountDBMockRecorder) GetBackend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackend", reflect.TypeOf((*MockDestroyedAccountDB)(nil).GetBackend))
}

// GetDestroyedAccounts mocks base method.
func (m *MockDestroyedAccountDB) GetDestroyedAccounts(block uint64, tx int) ([]types.Address, []types.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDestroyedAccounts", block, tx)
	ret0, _ := ret[0].([]types.Address)
	ret1, _ := ret[1].([]types.Address)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDestroyedAccounts indicates an expected call of GetDestroyedAccounts.
func (mr *MockDestroyedAccountDBMockRecorder) GetDestroyedAccounts(block, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDestroyedAccounts", reflect.TypeOf((*MockDestroyedAccountDB)(nil).GetDestroyedAccounts), block, tx)
}

// GetFirstKey mocks base method.
func (m *MockDestroyedAccountDB) GetFirstKey() (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstKey")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFirstKey indicates an expected call of GetFirstKey.
func (mr *MockDestroyedAccountDBMockRecorder) GetFirstKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstKey", reflect.TypeOf((*MockDestroyedAccountDB)(nil).GetFirstKey))
}

// GetLastKey mocks base method.
func (m *MockDestroyedAccountDB) GetLastKey() (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastKey")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastKey indicates an expected call of GetLastKey.
func (mr *MockDestroyedAccountDBMockRecorder) GetLastKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastKey", reflect.TypeOf((*MockDestroyedAccountDB)(nil).GetLastKey))
}

// Has mocks base method.
func (m *MockDestroyedAccountDB) Has(arg0 []byte) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Has", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Has indicates an expected call of Has.
func (mr *MockDestroyedAccountDBMockRecorder) Has(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Has", reflect.TypeOf((*MockDestroyedAccountDB)(nil).Has), arg0)
}

// NewBatch mocks base method.
func (m *MockDestroyedAccountDB) NewBatch() Batch {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewBatch")
	ret0, _ := ret[0].(Batch)
	return ret0
}

// NewBatch indicates an expected call of NewBatch.
func (mr *MockDestroyedAccountDBMockRecorder) NewBatch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewBatch", reflect.TypeOf((*MockDestroyedAccountDB)(nil).NewBatch))
}

// NewIterator mocks base method.
func (m *MockDestroyedAccountDB) NewIterator(prefix, start []byte) iterator.Iterator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewIterator", prefix, start)
	ret0, _ := ret[0].(iterator.Iterator)
	return ret0
}

// NewIterator indicates an expected call of NewIterator.
func (mr *MockDestroyedAccountDBMockRecorder) NewIterator(prefix, start any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewIterator", reflect.TypeOf((*MockDestroyedAccountDB)(nil).NewIterator), prefix, start)
}

// Put mocks base method.
func (m *MockDestroyedAccountDB) Put(key, value []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockDestroyedAccountDBMockRecorder) Put(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockDestroyedAccountDB)(nil).Put), key, value)
}

// SetDestroyedAccounts mocks base method.
func (m *MockDestroyedAccountDB) SetDestroyedAccounts(block uint64, tx int, destroyed, resurrected []types.Address) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDestroyedAccounts", block, tx, destroyed, resurrected)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDestroyedAccounts indicates an expected call of SetDestroyedAccounts.
func (mr *MockDestroyedAccountDBMockRecorder) SetDestroyedAccounts(block, tx, destroyed, resurrected any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDestroyedAccounts", reflect.TypeOf((*MockDestroyedAccountDB)(nil).SetDestroyedAccounts), block, tx, destroyed, resurrected)
}

// Stat mocks base method.
func (m *MockDestroyedAccountDB) Stat(property string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", property)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockDestroyedAccountDBMockRecorder) Stat(property any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockDestroyedAccountDB)(nil).Stat), property)
}

// binarySearchForLastPrefixKey mocks base method.
func (m *MockDestroyedAccountDB) binarySearchForLastPrefixKey(lastKeyPrefix []byte) (byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "binarySearchForLastPrefixKey", lastKeyPrefix)
	ret0, _ := ret[0].(byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// binarySearchForLastPrefixKey indicates an expected call of binarySearchForLastPrefixKey.
func (mr *MockDestroyedAccountDBMockRecorder) binarySearchForLastPrefixKey(lastKeyPrefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "binarySearchForLastPrefixKey", reflect.TypeOf((*MockDestroyedAccountDB)(nil).binarySearchForLastPrefixKey), lastKeyPrefix)
}

// hasKeyValuesFor mocks base method.
func (m *MockDestroyedAccountDB) hasKeyValuesFor(prefix, start []byte) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "hasKeyValuesFor", prefix, start)
	ret0, _ := ret[0].(bool)
	return ret0
}

// hasKeyValuesFor indicates an expected call of hasKeyValuesFor.
func (mr *MockDestroyedAccountDBMockRecorder) hasKeyValuesFor(prefix, start any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "hasKeyValuesFor", reflect.TypeOf((*MockDestroyedAccountDB)(nil).hasKeyValuesFor), prefix, start)
}

// newIterator mocks base method.
func (m *MockDestroyedAccountDB) newIterator(r *util.Range) iterator.Iterator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "newIterator", r)
	ret0, _ := ret[0].(iterator.Iterator)
	return ret0
}

// newIterator indicates an expected call of newIterator.
func (mr *MockDestroyedAccountDBMockRecorder) newIterator(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "newIterator", reflect.TypeOf((*MockDestroyedAccountDB)(nil).newIterator), r)
}

// stats mocks base method.
func (m *MockDestroyedAccountDB) stats(stats *leveldb.DBStats) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "stats", stats)
	ret0, _ := ret[0].(error)
	return ret0
}

// stats indicates an expected call of stats.
func (mr *MockDestroyedAccountDBMockRecorder) stats(stats any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "stats", reflect.TypeOf((*MockDestroyedAccountDB)(nil).stats), stats)
}
