// Code generated by MockGen. DO NOT EDIT.
// Source: exception_db.go
//
// Generated by this command:
//
//	mockgen -source=exception_db.go -destination=./exception_db_mock.go -package=db
//

// Package db is a generated GoMock package.
package db

import (
	reflect "reflect"

	substate "github.com/0xsoniclabs/substate/substate"
	leveldb "github.com/syndtr/goleveldb/leveldb"
	iterator "github.com/syndtr/goleveldb/leveldb/iterator"
	util "github.com/syndtr/goleveldb/leveldb/util"
	gomock "go.uber.org/mock/gomock"
)

// MockExceptionDB is a mock of ExceptionDB interface.
type MockExceptionDB struct {
	ctrl     *gomock.Controller
	recorder *MockExceptionDBMockRecorder
}

// MockExceptionDBMockRecorder is the mock recorder for MockExceptionDB.
type MockExceptionDBMockRecorder struct {
	mock *MockExceptionDB
}

// NewMockExceptionDB creates a new mock instance.
func NewMockExceptionDB(ctrl *gomock.Controller) *MockExceptionDB {
	mock := &MockExceptionDB{ctrl: ctrl}
	mock.recorder = &MockExceptionDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExceptionDB) EXPECT() *MockExceptionDBMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockExceptionDB) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockExceptionDBMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockExceptionDB)(nil).Close))
}

// Compact mocks base method.
func (m *MockExceptionDB) Compact(start, limit []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compact", start, limit)
	ret0, _ := ret[0].(error)
	return ret0
}

// Compact indicates an expected call of Compact.
func (mr *MockExceptionDBMockRecorder) Compact(start, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compact", reflect.TypeOf((*MockExceptionDB)(nil).Compact), start, limit)
}

// Delete mocks base method.
func (m *MockExceptionDB) Delete(key []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockExceptionDBMockRecorder) Delete(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockExceptionDB)(nil).Delete), key)
}

// Get mocks base method.
func (m *MockExceptionDB) Get(arg0 []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockExceptionDBMockRecorder) Get(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockExceptionDB)(nil).Get), arg0)
}

// GetException mocks base method.
func (m *MockExceptionDB) GetException(block uint64) (*substate.Exception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetException", block)
	ret0, _ := ret[0].(*substate.Exception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetException indicates an expected call of GetException.
func (mr *MockExceptionDBMockRecorder) GetException(block any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetException", reflect.TypeOf((*MockExceptionDB)(nil).GetException), block)
}

// GetFirstKey mocks base method.
func (m *MockExceptionDB) GetFirstKey() (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstKey")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFirstKey indicates an expected call of GetFirstKey.
func (mr *MockExceptionDBMockRecorder) GetFirstKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstKey", reflect.TypeOf((*MockExceptionDB)(nil).GetFirstKey))
}

// GetLastKey mocks base method.
func (m *MockExceptionDB) GetLastKey() (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastKey")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastKey indicates an expected call of GetLastKey.
func (mr *MockExceptionDBMockRecorder) GetLastKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastKey", reflect.TypeOf((*MockExceptionDB)(nil).GetLastKey))
}

// Has mocks base method.
func (m *MockExceptionDB) Has(arg0 []byte) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Has", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Has indicates an expected call of Has.
func (mr *MockExceptionDBMockRecorder) Has(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Has", reflect.TypeOf((*MockExceptionDB)(nil).Has), arg0)
}

// NewBatch mocks base method.
func (m *MockExceptionDB) NewBatch() Batch {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewBatch")
	ret0, _ := ret[0].(Batch)
	return ret0
}

// NewBatch indicates an expected call of NewBatch.
func (mr *MockExceptionDBMockRecorder) NewBatch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewBatch", reflect.TypeOf((*MockExceptionDB)(nil).NewBatch))
}

// NewExceptionIterator mocks base method.
func (m *MockExceptionDB) NewExceptionIterator(start, numWorkers int) IIterator[*substate.Exception] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewExceptionIterator", start, numWorkers)
	ret0, _ := ret[0].(IIterator[*substate.Exception])
	return ret0
}

// NewExceptionIterator indicates an expected call of NewExceptionIterator.
func (mr *MockExceptionDBMockRecorder) NewExceptionIterator(start, numWorkers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewExceptionIterator", reflect.TypeOf((*MockExceptionDB)(nil).NewExceptionIterator), start, numWorkers)
}

// NewIterator mocks base method.
func (m *MockExceptionDB) NewIterator(prefix, start []byte) iterator.Iterator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewIterator", prefix, start)
	ret0, _ := ret[0].(iterator.Iterator)
	return ret0
}

// NewIterator indicates an expected call of NewIterator.
func (mr *MockExceptionDBMockRecorder) NewIterator(prefix, start any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewIterator", reflect.TypeOf((*MockExceptionDB)(nil).NewIterator), prefix, start)
}

// Put mocks base method.
func (m *MockExceptionDB) Put(key, value []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockExceptionDBMockRecorder) Put(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockExceptionDB)(nil).Put), key, value)
}

// PutException mocks base method.
func (m *MockExceptionDB) PutException(e *substate.Exception) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutException", e)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutException indicates an expected call of PutException.
func (mr *MockExceptionDBMockRecorder) PutException(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutException", reflect.TypeOf((*MockExceptionDB)(nil).PutException), e)
}

// Stat mocks base method.
func (m *MockExceptionDB) Stat(property string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", property)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockExceptionDBMockRecorder) Stat(property any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockExceptionDB)(nil).Stat), property)
}

// binarySearchForLastPrefixKey mocks base method.
func (m *MockExceptionDB) binarySearchForLastPrefixKey(lastKeyPrefix []byte) (byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "binarySearchForLastPrefixKey", lastKeyPrefix)
	ret0, _ := ret[0].(byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// binarySearchForLastPrefixKey indicates an expected call of binarySearchForLastPrefixKey.
func (mr *MockExceptionDBMockRecorder) binarySearchForLastPrefixKey(lastKeyPrefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "binarySearchForLastPrefixKey", reflect.TypeOf((*MockExceptionDB)(nil).binarySearchForLastPrefixKey), lastKeyPrefix)
}

// decodeToException mocks base method.
func (m *MockExceptionDB) decodeToException(data []byte, block uint64) (*substate.Exception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "decodeToException", data, block)
	ret0, _ := ret[0].(*substate.Exception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// decodeToException indicates an expected call of decodeToException.
func (mr *MockExceptionDBMockRecorder) decodeToException(data, block any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "decodeToException", reflect.TypeOf((*MockExceptionDB)(nil).decodeToException), data, block)
}

// getBackend mocks base method.
func (m *MockExceptionDB) getBackend() dbAdapter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getBackend")
	ret0, _ := ret[0].(dbAdapter)
	return ret0
}

// getBackend indicates an expected call of getBackend.
func (mr *MockExceptionDBMockRecorder) getBackend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getBackend", reflect.TypeOf((*MockExceptionDB)(nil).getBackend))
}

// hasKeyValuesFor mocks base method.
func (m *MockExceptionDB) hasKeyValuesFor(prefix, start []byte) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "hasKeyValuesFor", prefix, start)
	ret0, _ := ret[0].(bool)
	return ret0
}

// hasKeyValuesFor indicates an expected call of hasKeyValuesFor.
func (mr *MockExceptionDBMockRecorder) hasKeyValuesFor(prefix, start any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "hasKeyValuesFor", reflect.TypeOf((*MockExceptionDB)(nil).hasKeyValuesFor), prefix, start)
}

// newIterator mocks base method.
func (m *MockExceptionDB) newIterator(r *util.Range) iterator.Iterator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "newIterator", r)
	ret0, _ := ret[0].(iterator.Iterator)
	return ret0
}

// newIterator indicates an expected call of newIterator.
func (mr *MockExceptionDBMockRecorder) newIterator(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "newIterator", reflect.TypeOf((*MockExceptionDB)(nil).newIterator), r)
}

// stats mocks base method.
func (m *MockExceptionDB) stats(stats *leveldb.DBStats) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "stats", stats)
	ret0, _ := ret[0].(error)
	return ret0
}

// stats indicates an expected call of stats.
func (mr *MockExceptionDBMockRecorder) stats(stats any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "stats", reflect.TypeOf((*MockExceptionDB)(nil).stats), stats)
}
