// Code generated by MockGen. DO NOT EDIT.
// Source: hash_provider.go
//
// Generated by this command:
//
//	mockgen -source hash_provider.go -destination hash_provider_mock.go -package db
//

// Package db is a generated GoMock package.
package db

import (
	reflect "reflect"

	types "github.com/0xsoniclabs/substate/types"
	gomock "go.uber.org/mock/gomock"
)

// MockIRpcClient is a mock of IRpcClient interface.
type MockIRpcClient struct {
	ctrl     *gomock.Controller
	recorder *MockIRpcClientMockRecorder
}

// MockIRpcClientMockRecorder is the mock recorder for MockIRpcClient.
type MockIRpcClientMockRecorder struct {
	mock *MockIRpcClient
}

// NewMockIRpcClient creates a new mock instance.
func NewMockIRpcClient(ctrl *gomock.Controller) *MockIRpcClient {
	mock := &MockIRpcClient{ctrl: ctrl}
	mock.recorder = &MockIRpcClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRpcClient) EXPECT() *MockIRpcClientMockRecorder {
	return m.recorder
}

// Call mocks base method.
func (m *MockIRpcClient) Call(result any, method string, args ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{result, method}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Call", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Call indicates an expected call of Call.
func (mr *MockIRpcClientMockRecorder) Call(result, method any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{result, method}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Call", reflect.TypeOf((*MockIRpcClient)(nil).Call), varargs...)
}

// MockHashProvider is a mock of HashProvider interface.
type MockHashProvider struct {
	ctrl     *gomock.Controller
	recorder *MockHashProviderMockRecorder
}

// MockHashProviderMockRecorder is the mock recorder for MockHashProvider.
type MockHashProviderMockRecorder struct {
	mock *MockHashProvider
}

// NewMockHashProvider creates a new mock instance.
func NewMockHashProvider(ctrl *gomock.Controller) *MockHashProvider {
	mock := &MockHashProvider{ctrl: ctrl}
	mock.recorder = &MockHashProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHashProvider) EXPECT() *MockHashProviderMockRecorder {
	return m.recorder
}

// GetBlockHash mocks base method.
func (m *MockHashProvider) GetBlockHash(blockNumber int) (types.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockHash", blockNumber)
	ret0, _ := ret[0].(types.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockHash indicates an expected call of GetBlockHash.
func (mr *MockHashProviderMockRecorder) GetBlockHash(blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockHash", reflect.TypeOf((*MockHashProvider)(nil).GetBlockHash), blockNumber)
}

// GetStateRootHash mocks base method.
func (m *MockHashProvider) GetStateRootHash(blockNumber int) (types.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStateRootHash", blockNumber)
	ret0, _ := ret[0].(types.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStateRootHash indicates an expected call of GetStateRootHash.
func (mr *MockHashProviderMockRecorder) GetStateRootHash(blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStateRootHash", reflect.TypeOf((*MockHashProvider)(nil).GetStateRootHash), blockNumber)
}
