// Code generated by MockGen. DO NOT EDIT.
// Source: iterator.go
//
// Generated by this command:
//
//	mockgen -source=iterator.go -destination=./iterator_mock.go -package=db
//

// Package db is a generated GoMock package.
package db

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIIterator is a mock of IIterator interface.
type MockIIterator[T comparable] struct {
	ctrl     *gomock.Controller
	recorder *MockIIteratorMockRecorder[T]
	isgomock struct{}
}

// MockIIteratorMockRecorder is the mock recorder for MockIIterator.
type MockIIteratorMockRecorder[T comparable] struct {
	mock *MockIIterator[T]
}

// NewMockIIterator creates a new mock instance.
func NewMockIIterator[T comparable](ctrl *gomock.Controller) *MockIIterator[T] {
	mock := &MockIIterator[T]{ctrl: ctrl}
	mock.recorder = &MockIIteratorMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIIterator[T]) EXPECT() *MockIIteratorMockRecorder[T] {
	return m.recorder
}

// Error mocks base method.
func (m *MockIIterator[T]) Error() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error")
	ret0, _ := ret[0].(error)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MockIIteratorMockRecorder[T]) Error() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockIIterator[T])(nil).Error))
}

// Next mocks base method.
func (m *MockIIterator[T]) Next() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Next indicates an expected call of Next.
func (mr *MockIIteratorMockRecorder[T]) Next() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockIIterator[T])(nil).Next))
}

// Release mocks base method.
func (m *MockIIterator[T]) Release() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release")
}

// Release indicates an expected call of Release.
func (mr *MockIIteratorMockRecorder[T]) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockIIterator[T])(nil).Release))
}

// Value mocks base method.
func (m *MockIIterator[T]) Value() T {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Value")
	ret0, _ := ret[0].(T)
	return ret0
}

// Value indicates an expected call of Value.
func (mr *MockIIteratorMockRecorder[T]) Value() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Value", reflect.TypeOf((*MockIIterator[T])(nil).Value))
}

// decode mocks base method.
func (m *MockIIterator[T]) decode(data rawEntry) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "decode", data)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// decode indicates an expected call of decode.
func (mr *MockIIteratorMockRecorder[T]) decode(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "decode", reflect.TypeOf((*MockIIterator[T])(nil).decode), data)
}

// start mocks base method.
func (m *MockIIterator[T]) start(numWorkers int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "start", numWorkers)
}

// start indicates an expected call of start.
func (mr *MockIIteratorMockRecorder[T]) start(numWorkers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "start", reflect.TypeOf((*MockIIterator[T])(nil).start), numWorkers)
}
