// Code generated by MockGen. DO NOT EDIT.
// Source: state_hash_db.go
//
// Generated by this command:
//
//	mockgen -source=state_hash_db.go -destination=./state_hash_db_mock.go -package=db
//

// Package db is a generated GoMock package.
package db

import (
	reflect "reflect"

	types "github.com/0xsoniclabs/substate/types"
	leveldb "github.com/syndtr/goleveldb/leveldb"
	iterator "github.com/syndtr/goleveldb/leveldb/iterator"
	util "github.com/syndtr/goleveldb/leveldb/util"
	gomock "go.uber.org/mock/gomock"
)

// MockStateHashDB is a mock of StateHashDB interface.
type MockStateHashDB struct {
	ctrl     *gomock.Controller
	recorder *MockStateHashDBMockRecorder
}

// MockStateHashDBMockRecorder is the mock recorder for MockStateHashDB.
type MockStateHashDBMockRecorder struct {
	mock *MockStateHashDB
}

// NewMockStateHashDB creates a new mock instance.
func NewMockStateHashDB(ctrl *gomock.Controller) *MockStateHashDB {
	mock := &MockStateHashDB{ctrl: ctrl}
	mock.recorder = &MockStateHashDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateHashDB) EXPECT() *MockStateHashDBMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockStateHashDB) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockStateHashDBMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStateHashDB)(nil).Close))
}

// Compact mocks base method.
func (m *MockStateHashDB) Compact(start, limit []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compact", start, limit)
	ret0, _ := ret[0].(error)
	return ret0
}

// Compact indicates an expected call of Compact.
func (mr *MockStateHashDBMockRecorder) Compact(start, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compact", reflect.TypeOf((*MockStateHashDB)(nil).Compact), start, limit)
}

// Delete mocks base method.
func (m *MockStateHashDB) Delete(key []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStateHashDBMockRecorder) Delete(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStateHashDB)(nil).Delete), key)
}

// Get mocks base method.
func (m *MockStateHashDB) Get(arg0 []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStateHashDBMockRecorder) Get(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStateHashDB)(nil).Get), arg0)
}

// GetBackend mocks base method.
func (m *MockStateHashDB) GetBackend() DbAdapter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackend")
	ret0, _ := ret[0].(DbAdapter)
	return ret0
}

// GetBackend indicates an expected call of GetBackend.
func (mr *MockStateHashDBMockRecorder) GetBackend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackend", reflect.TypeOf((*MockStateHashDB)(nil).GetBackend))
}

// GetFirstKey mocks base method.
func (m *MockStateHashDB) GetFirstKey() (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstKey")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFirstKey indicates an expected call of GetFirstKey.
func (mr *MockStateHashDBMockRecorder) GetFirstKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstKey", reflect.TypeOf((*MockStateHashDB)(nil).GetFirstKey))
}

// GetLastKey mocks base method.
func (m *MockStateHashDB) GetLastKey() (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastKey")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastKey indicates an expected call of GetLastKey.
func (mr *MockStateHashDBMockRecorder) GetLastKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastKey", reflect.TypeOf((*MockStateHashDB)(nil).GetLastKey))
}

// GetStateHash mocks base method.
func (m *MockStateHashDB) GetStateHash(block int) (types.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStateHash", block)
	ret0, _ := ret[0].(types.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStateHash indicates an expected call of GetStateHash.
func (mr *MockStateHashDBMockRecorder) GetStateHash(block any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStateHash", reflect.TypeOf((*MockStateHashDB)(nil).GetStateHash), block)
}

// GetSubstateEncoding mocks base method.
func (m *MockStateHashDB) GetSubstateEncoding() SubstateEncodingSchema {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubstateEncoding")
	ret0, _ := ret[0].(SubstateEncodingSchema)
	return ret0
}

// GetSubstateEncoding indicates an expected call of GetSubstateEncoding.
func (mr *MockStateHashDBMockRecorder) GetSubstateEncoding() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubstateEncoding", reflect.TypeOf((*MockStateHashDB)(nil).GetSubstateEncoding))
}

// Has mocks base method.
func (m *MockStateHashDB) Has(arg0 []byte) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Has", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Has indicates an expected call of Has.
func (mr *MockStateHashDBMockRecorder) Has(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Has", reflect.TypeOf((*MockStateHashDB)(nil).Has), arg0)
}

// NewBatch mocks base method.
func (m *MockStateHashDB) NewBatch() Batch {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewBatch")
	ret0, _ := ret[0].(Batch)
	return ret0
}

// NewBatch indicates an expected call of NewBatch.
func (mr *MockStateHashDBMockRecorder) NewBatch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewBatch", reflect.TypeOf((*MockStateHashDB)(nil).NewBatch))
}

// NewIterator mocks base method.
func (m *MockStateHashDB) NewIterator(prefix, start []byte) iterator.Iterator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewIterator", prefix, start)
	ret0, _ := ret[0].(iterator.Iterator)
	return ret0
}

// NewIterator indicates an expected call of NewIterator.
func (mr *MockStateHashDBMockRecorder) NewIterator(prefix, start any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewIterator", reflect.TypeOf((*MockStateHashDB)(nil).NewIterator), prefix, start)
}

// Put mocks base method.
func (m *MockStateHashDB) Put(key, value []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockStateHashDBMockRecorder) Put(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockStateHashDB)(nil).Put), key, value)
}

// PutStateHash mocks base method.
func (m *MockStateHashDB) PutStateHash(blockNumber uint64, stateHash []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutStateHash", blockNumber, stateHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutStateHash indicates an expected call of PutStateHash.
func (mr *MockStateHashDBMockRecorder) PutStateHash(blockNumber, stateHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutStateHash", reflect.TypeOf((*MockStateHashDB)(nil).PutStateHash), blockNumber, stateHash)
}

// PutStateHashString mocks base method.
func (m *MockStateHashDB) PutStateHashString(blockNumberHex, stateHashString string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutStateHashString", blockNumberHex, stateHashString)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutStateHashString indicates an expected call of PutStateHashString.
func (mr *MockStateHashDBMockRecorder) PutStateHashString(blockNumberHex, stateHashString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutStateHashString", reflect.TypeOf((*MockStateHashDB)(nil).PutStateHashString), blockNumberHex, stateHashString)
}

// Stat mocks base method.
func (m *MockStateHashDB) Stat(property string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", property)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockStateHashDBMockRecorder) Stat(property any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockStateHashDB)(nil).Stat), property)
}

// binarySearchForLastPrefixKey mocks base method.
func (m *MockStateHashDB) binarySearchForLastPrefixKey(lastKeyPrefix []byte) (byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "binarySearchForLastPrefixKey", lastKeyPrefix)
	ret0, _ := ret[0].(byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// binarySearchForLastPrefixKey indicates an expected call of binarySearchForLastPrefixKey.
func (mr *MockStateHashDBMockRecorder) binarySearchForLastPrefixKey(lastKeyPrefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "binarySearchForLastPrefixKey", reflect.TypeOf((*MockStateHashDB)(nil).binarySearchForLastPrefixKey), lastKeyPrefix)
}

// hasKeyValuesFor mocks base method.
func (m *MockStateHashDB) hasKeyValuesFor(prefix, start []byte) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "hasKeyValuesFor", prefix, start)
	ret0, _ := ret[0].(bool)
	return ret0
}

// hasKeyValuesFor indicates an expected call of hasKeyValuesFor.
func (mr *MockStateHashDBMockRecorder) hasKeyValuesFor(prefix, start any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "hasKeyValuesFor", reflect.TypeOf((*MockStateHashDB)(nil).hasKeyValuesFor), prefix, start)
}

// newIterator mocks base method.
func (m *MockStateHashDB) newIterator(r *util.Range) iterator.Iterator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "newIterator", r)
	ret0, _ := ret[0].(iterator.Iterator)
	return ret0
}

// newIterator indicates an expected call of newIterator.
func (mr *MockStateHashDBMockRecorder) newIterator(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "newIterator", reflect.TypeOf((*MockStateHashDB)(nil).newIterator), r)
}

// stats mocks base method.
func (m *MockStateHashDB) stats(stats *leveldb.DBStats) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "stats", stats)
	ret0, _ := ret[0].(error)
	return ret0
}

// stats indicates an expected call of stats.
func (mr *MockStateHashDBMockRecorder) stats(stats any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "stats", reflect.TypeOf((*MockStateHashDB)(nil).stats), stats)
}
