// Code generated by MockGen. DO NOT EDIT.
// Source: substate_db.go
//
// Generated by this command:
//
//	mockgen -source=substate_db.go -destination=./substate_db_mock.go -package=db
//

// Package db is a generated GoMock package.
package db

import (
	reflect "reflect"

	substate "github.com/0xsoniclabs/substate/substate"
	types "github.com/0xsoniclabs/substate/types"
	leveldb "github.com/syndtr/goleveldb/leveldb"
	iterator "github.com/syndtr/goleveldb/leveldb/iterator"
	cli "github.com/urfave/cli/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockSubstateDB is a mock of SubstateDB interface.
type MockSubstateDB struct {
	ctrl     *gomock.Controller
	recorder *MockSubstateDBMockRecorder
	isgomock struct{}
}

// MockSubstateDBMockRecorder is the mock recorder for MockSubstateDB.
type MockSubstateDBMockRecorder struct {
	mock *MockSubstateDB
}

// NewMockSubstateDB creates a new mock instance.
func NewMockSubstateDB(ctrl *gomock.Controller) *MockSubstateDB {
	mock := &MockSubstateDB{ctrl: ctrl}
	mock.recorder = &MockSubstateDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubstateDB) EXPECT() *MockSubstateDBMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockSubstateDB) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSubstateDBMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSubstateDB)(nil).Close))
}

// Compact mocks base method.
func (m *MockSubstateDB) Compact(start, limit []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compact", start, limit)
	ret0, _ := ret[0].(error)
	return ret0
}

// Compact indicates an expected call of Compact.
func (mr *MockSubstateDBMockRecorder) Compact(start, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compact", reflect.TypeOf((*MockSubstateDB)(nil).Compact), start, limit)
}

// Delete mocks base method.
func (m *MockSubstateDB) Delete(key []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSubstateDBMockRecorder) Delete(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSubstateDB)(nil).Delete), key)
}

// DeleteCode mocks base method.
func (m *MockSubstateDB) DeleteCode(arg0 types.Hash) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCode", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCode indicates an expected call of DeleteCode.
func (mr *MockSubstateDBMockRecorder) DeleteCode(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCode", reflect.TypeOf((*MockSubstateDB)(nil).DeleteCode), arg0)
}

// DeleteSubstate mocks base method.
func (m *MockSubstateDB) DeleteSubstate(block uint64, tx int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubstate", block, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubstate indicates an expected call of DeleteSubstate.
func (mr *MockSubstateDBMockRecorder) DeleteSubstate(block, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubstate", reflect.TypeOf((*MockSubstateDB)(nil).DeleteSubstate), block, tx)
}

// Get mocks base method.
func (m *MockSubstateDB) Get(arg0 []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSubstateDBMockRecorder) Get(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSubstateDB)(nil).Get), arg0)
}

// GetBlockSubstates mocks base method.
func (m *MockSubstateDB) GetBlockSubstates(block uint64) (map[int]*substate.Substate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockSubstates", block)
	ret0, _ := ret[0].(map[int]*substate.Substate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockSubstates indicates an expected call of GetBlockSubstates.
func (mr *MockSubstateDBMockRecorder) GetBlockSubstates(block any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockSubstates", reflect.TypeOf((*MockSubstateDB)(nil).GetBlockSubstates), block)
}

// GetCode mocks base method.
func (m *MockSubstateDB) GetCode(arg0 types.Hash) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCode", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCode indicates an expected call of GetCode.
func (mr *MockSubstateDBMockRecorder) GetCode(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCode", reflect.TypeOf((*MockSubstateDB)(nil).GetCode), arg0)
}

// GetFirstSubstate mocks base method.
func (m *MockSubstateDB) GetFirstSubstate() *substate.Substate {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstSubstate")
	ret0, _ := ret[0].(*substate.Substate)
	return ret0
}

// GetFirstSubstate indicates an expected call of GetFirstSubstate.
func (mr *MockSubstateDBMockRecorder) GetFirstSubstate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstSubstate", reflect.TypeOf((*MockSubstateDB)(nil).GetFirstSubstate))
}

// GetLastSubstate mocks base method.
func (m *MockSubstateDB) GetLastSubstate() (*substate.Substate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastSubstate")
	ret0, _ := ret[0].(*substate.Substate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastSubstate indicates an expected call of GetLastSubstate.
func (mr *MockSubstateDBMockRecorder) GetLastSubstate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastSubstate", reflect.TypeOf((*MockSubstateDB)(nil).GetLastSubstate))
}

// GetSubstate mocks base method.
func (m *MockSubstateDB) GetSubstate(block uint64, tx int) (*substate.Substate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubstate", block, tx)
	ret0, _ := ret[0].(*substate.Substate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubstate indicates an expected call of GetSubstate.
func (mr *MockSubstateDBMockRecorder) GetSubstate(block, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubstate", reflect.TypeOf((*MockSubstateDB)(nil).GetSubstate), block, tx)
}

// GetSubstateEncoding mocks base method.
func (m *MockSubstateDB) GetSubstateEncoding() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubstateEncoding")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSubstateEncoding indicates an expected call of GetSubstateEncoding.
func (mr *MockSubstateDBMockRecorder) GetSubstateEncoding() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubstateEncoding", reflect.TypeOf((*MockSubstateDB)(nil).GetSubstateEncoding))
}

// Has mocks base method.
func (m *MockSubstateDB) Has(arg0 []byte) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Has", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Has indicates an expected call of Has.
func (mr *MockSubstateDBMockRecorder) Has(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Has", reflect.TypeOf((*MockSubstateDB)(nil).Has), arg0)
}

// HasCode mocks base method.
func (m *MockSubstateDB) HasCode(arg0 types.Hash) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasCode", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasCode indicates an expected call of HasCode.
func (mr *MockSubstateDBMockRecorder) HasCode(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasCode", reflect.TypeOf((*MockSubstateDB)(nil).HasCode), arg0)
}

// HasSubstate mocks base method.
func (m *MockSubstateDB) HasSubstate(block uint64, tx int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasSubstate", block, tx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasSubstate indicates an expected call of HasSubstate.
func (mr *MockSubstateDBMockRecorder) HasSubstate(block, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasSubstate", reflect.TypeOf((*MockSubstateDB)(nil).HasSubstate), block, tx)
}

// NewBatch mocks base method.
func (m *MockSubstateDB) NewBatch() Batch {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewBatch")
	ret0, _ := ret[0].(Batch)
	return ret0
}

// NewBatch indicates an expected call of NewBatch.
func (mr *MockSubstateDBMockRecorder) NewBatch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewBatch", reflect.TypeOf((*MockSubstateDB)(nil).NewBatch))
}

// NewIterator mocks base method.
func (m *MockSubstateDB) NewIterator(prefix, start []byte) iterator.Iterator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewIterator", prefix, start)
	ret0, _ := ret[0].(iterator.Iterator)
	return ret0
}

// NewIterator indicates an expected call of NewIterator.
func (mr *MockSubstateDBMockRecorder) NewIterator(prefix, start any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewIterator", reflect.TypeOf((*MockSubstateDB)(nil).NewIterator), prefix, start)
}

// NewSubstateIterator mocks base method.
func (m *MockSubstateDB) NewSubstateIterator(start, numWorkers int) IIterator[*substate.Substate] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSubstateIterator", start, numWorkers)
	ret0, _ := ret[0].(IIterator[*substate.Substate])
	return ret0
}

// NewSubstateIterator indicates an expected call of NewSubstateIterator.
func (mr *MockSubstateDBMockRecorder) NewSubstateIterator(start, numWorkers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSubstateIterator", reflect.TypeOf((*MockSubstateDB)(nil).NewSubstateIterator), start, numWorkers)
}

// NewSubstateTaskPool mocks base method.
func (m *MockSubstateDB) NewSubstateTaskPool(name string, taskFunc SubstateTaskFunc, first, last uint64, ctx *cli.Context) *SubstateTaskPool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSubstateTaskPool", name, taskFunc, first, last, ctx)
	ret0, _ := ret[0].(*SubstateTaskPool)
	return ret0
}

// NewSubstateTaskPool indicates an expected call of NewSubstateTaskPool.
func (mr *MockSubstateDBMockRecorder) NewSubstateTaskPool(name, taskFunc, first, last, ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSubstateTaskPool", reflect.TypeOf((*MockSubstateDB)(nil).NewSubstateTaskPool), name, taskFunc, first, last, ctx)
}

// Put mocks base method.
func (m *MockSubstateDB) Put(key, value []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockSubstateDBMockRecorder) Put(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockSubstateDB)(nil).Put), key, value)
}

// PutCode mocks base method.
func (m *MockSubstateDB) PutCode(arg0 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutCode", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutCode indicates an expected call of PutCode.
func (mr *MockSubstateDBMockRecorder) PutCode(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutCode", reflect.TypeOf((*MockSubstateDB)(nil).PutCode), arg0)
}

// PutSubstate mocks base method.
func (m *MockSubstateDB) PutSubstate(substate *substate.Substate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutSubstate", substate)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutSubstate indicates an expected call of PutSubstate.
func (mr *MockSubstateDBMockRecorder) PutSubstate(substate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutSubstate", reflect.TypeOf((*MockSubstateDB)(nil).PutSubstate), substate)
}

// SetSubstateEncoding mocks base method.
func (m *MockSubstateDB) SetSubstateEncoding(encoding string) (*substateDB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSubstateEncoding", encoding)
	ret0, _ := ret[0].(*substateDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetSubstateEncoding indicates an expected call of SetSubstateEncoding.
func (mr *MockSubstateDBMockRecorder) SetSubstateEncoding(encoding any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSubstateEncoding", reflect.TypeOf((*MockSubstateDB)(nil).SetSubstateEncoding), encoding)
}

// Stat mocks base method.
func (m *MockSubstateDB) Stat(property string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", property)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockSubstateDBMockRecorder) Stat(property any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockSubstateDB)(nil).Stat), property)
}

// getBackend mocks base method.
func (m *MockSubstateDB) getBackend() *leveldb.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getBackend")
	ret0, _ := ret[0].(*leveldb.DB)
	return ret0
}

// getBackend indicates an expected call of getBackend.
func (mr *MockSubstateDBMockRecorder) getBackend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getBackend", reflect.TypeOf((*MockSubstateDB)(nil).getBackend))
}
